# -*- coding: utf-8 -*-
"""Crea un grafico circular

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6ZK_GVYtJf0falzmTF9CWp6jyzQBu-0
"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

slices = [59219, 55466, 47544, 36443, 35917]
labels = ["JavaScript", 'HTML/CSS', 'SQL', 'Python', 'Java']
explode = [0, 0, 0, 0.1, 0]

plt.pie(slices, labels=labels, explode=explode, shadow=True,
        startangle=90, autopct="%1f%%",
        wedgeprops={"edgecolor": "black"})

plt.title("My Awesome Pie Chart")
plt.tight_layout()
plt.show()